version: '3'

services:
  gitea:
    image: gitea/gitea:1.9.3
    ports:
      - '3000:3000'
    volumes:
      - gitea_data:/data
  jenkins:
    build: dockerfile/jenkins
    ports:
      - '4440:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
  dozzle:
    image: amir20/dozzle:v1.15.7
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitea_data:
  jenkins_home:
